experiment_name: 'multimodal_classifier'
phase: 'classification'

lightning:
    trainer:
       gpus: '0'
       max_epochs: 50
       distributed_backend: 'dp'
       gradient_clip_val: 0.25
       lr: 0.00005  # 0.00005
       precision: 32  # 16
    checkpoint_callback:
        monitor: 'val_auroc'
        dirpath: './data/ckpt'
        save_last: true 
        mode: max
        save_top_k: 5
    early_stopping_callback:
        monitor: 'val_loss'
        min_delta: 0.00
        patience: 10 # 10
        verbose: False
        mode: 'min' # max表示monitor越大越好，min表示monitor越小越好
    logger:
        logger_type: 'WandbLogger'
        save_dir: './data/'
        project: 'mglrl'

model:
    norm: false
    mglrl:
        b_model: True  #  False
    vision:
        model_name: 'resnet_50'
        freeze_cnn: false
        pretrained: true
        num_targets: 3 # 3
    text:
        bert_type: "emilyalsentzer/Bio_ClinicalBERT"
        last_n_layers: 4
        aggregate_method: 'sum'
        norm: false
        embedding_dim: 768
        freeze_bert: false
        agg_tokens: true

data: 
    dataset: custom
    text: 
      word_num: 97
    image:
        imsize: 256
    data_type: custom

transforms: 
    norm: 'half'
    random_crop:
        crop_size: 224

train: 
    update_interval: 1  #  1000
    batch_size: 16    #  48  16
    num_workers: 18   # 18
    optimizer: 
        name: 'Adam'
        weight_decay: 1e-6
    scheduler: 
        name: 'plateau'
        monitor: 'val_loss'
        interval: 'epoch'
        frequency: 1
